version: "3"

services:
  db:
    container_name: hh_psql
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=hh
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=overwritethisinprod!
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 10s
      retries: 50
    ports:
      - "5432:5432"
  pgadmin:
    container_name: hh_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:
